keys:
  - &admin_waciejm age15vp4zzpzw4zk2590a7nq0yjtza6twemyqkqx048rm6wdxs7jesus5tx8m0
  # echo PUBLIC_HOST_KEY | nix run nixpkgs#ssh-to-age
  - &machine_bolek age1y5lxn455xv70gkf6h6jycpr4nakm3c2d9ngd40h0deyft6ezgals36sl2z
creation_rules:
  - path_regex: '^systems/bolek/secrets/[^/]+\.sops\.[^/]+$'
    key_groups:
      - age:
          - *admin_waciejm
          - *machine_bolek
