#!/usr/bin/env bash
set -euo pipefail

export NIX_CONFIG="experimental-features = nix-command flakes"

if [[ "$OSTYPE" == "linux"* ]]; then
	if [[ "$(uname -a)" == *"aarch64"* ]]; then
		export HOME_PROFILE_VARIANT="linux-aarch64"
	else
		export HOME_PROFILE_VARIANT="linux-x86_64"
	fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
	if [[ "$(uname -a)" == *"arm64"* ]]; then
		export HOME_PROFILE_VARIANT="macos-aarch64"
	else
		export HOME_PROFILE_VARIANT="macos-x86_64"
	fi
fi

PS4="+> "
set -x

nix run .#home-manager -- switch --flake .#waciejm-${HOME_PROFILE_VARIANT}
