#!/usr/bin/env bash
set -euo pipefail

export NIX_CONFIG="experimental-features = nix-command flakes"

if [[ "$OSTYPE" == "linux"* ]]; then
	if [[ "$(uname -a)" == *"aarch64"* ]]; then
		export HOME_PROFILE_VARIANT="linux-arm"
	else
		export HOME_PROFILE_VARIANT="linux"
	fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
	export HOME_PROFILE_VARIANT="macos"
fi

PS4="+> "
set -x

nix run .#home-manager -- switch --flake .#waciejm-${HOME_PROFILE_VARIANT}
