format = """
$time$username$hostname$directory$cmd_duration
$git_branch$git_status$git_state$rust$python$package
$shlvl$status[ » ](bold green)
"""

[username]
show_always = true
format = "[$user]($style)"

[hostname]
ssh_only = false
format = "[@$hostname ]($style)"

[time]
disabled = false
format = "[$time ]($style)"

[directory]
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style) "

[cmd_duration]
min_time = 1_000

[status]
disabled = false
format = "[$symbol $status]($style)"

[shlvl]
disabled = false
