## exec Hyprland if in TTY1

if [[ "$TTY" = "/dev/tty1" ]] then
	exec Hyprland
fi


## setup nix

if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix.sh'
fi


## setup PATH

# homebrew

if [[ "$OSTYPE" == "darwin"* ]]; then
	export PATH="/opt/homebrew/bin:$PATH"
fi


## setup zsh

fpath+=~/.zfunc
autoload -Uz compinit && compinit

setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

HISTFILE=$HOME/.zhistory
HISTSIZE=100000
SAVEHIST=100000

# Disable terminal controls bound by default to ^Q ^S ^U ^O ^V ^R ^W
stty start undef stop undef kill undef
stty discard undef lnext undef rprnt undef werase undef


## setup starship

eval "$(starship init zsh)"


## setup zoxide

eval "$(zoxide init --cmd cd zsh)"


## setup ssh-agent

if [[ "$OSTYPE" == "darwin"* ]]; then
	ssh-add --apple-load-keychain 2> /dev/null
elif [[ "$OSTYPE" == "linux"* ]]; then
	if [[ -z "$SSH_AUTH_SOCK" ]]; then
		eval $(/run/wrappers/bin/gnome-keyring-daemon --start --daemonize 2>/dev/null)
		export SSH_AUTH_SOCK
	fi
fi


## setup aliases

# ls
alias l="lsd -l"
alias ls=lsd
alias la="lsd -lA"

# git
alias glog="git log --all --oneline --graph"
alias gca="git commit --amend"
alias gc="git commit"
alias gaa="git add ."
alias gr="git review"
alias gs="git status"
alias gd="git diff"

# sops
alias homesops="SOPS_AGE_KEY=\$(age -d ~/Keys/homeops.age) sops"

# rip
alias rip="rip --graveyard ~/.graveyard"
alias ripu="rip --graveyard ~/.graveyard --unbury"
alias ripd="rip --graveyard ~/.graveyard --decompose"
