#!/usr/bin/env bash

set -e

ERRORMSG="stream - play twitch streams in iina\n\n  usage: twitch <channel> <quality>"

if [[ -z "$1" ]]; then
	echo -e "$ERRORMSG"
	exit 1
elif [[ -z "$2" ]]; then
	streamlink https://www.twitch.tv/$1
elif [[ -z "$3" ]]; then
	streamlink --stdout https://www.twitch.tv/$1 $2 | iina --stdin
else
	echo -e "$ERRORMSG"
	exit 1
fi

