#!/usr/bin/env zsh

if [ "$HOST" = "badura" ]; then
	easyeffects --gapplication-service &
	waybar &
	swww init & 
	blueman-applet &
	pasystray &
	nextcloud --background &

	sleep 1

	swww img $(random-wallpaper) &
	google-chrome-stable &
	firefox &

	sleep 2

	slack &
	alacritty --class ncspot --command ncspot &

	sleep 2

	obsidian &
	signal-desktop &
fi
