#!/usr/bin/env zsh

if [ "$HOST" = "badura" ]; then
	# tray
	nextcloud --background &
	blueman-applet &
	steam -forcedesktopscaling=1 -nochatui -nofriendsui -silent &

	# browsers
	google-chrome-stable &
	firefox &

	# communicators
	slack &
	thunderbird &
	signal-desktop &

	# org
	obsidian &

	# audio
	easyeffects &
	alacritty --class ncspot --command ncspot &
fi
