#!/usr/bin/env zsh

if [ "$HOST" = "badura" ]; then
	nextcloud --background &
	blueman-applet &
	steam -forcedesktopscaling=1 -nochatui -nofriendsui -silent &

	google-chrome-stable &
	slack &
	obsidian &
	firefox &
	signal-desktop &
	alacritty --class ncspot --command ncspot &
	pavucontrol &
	easyeffects &
fi
